//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.NoiThat.Core
{
	/// <summary>About Us Controls</summary>
	[PublishedModel("aboutUsControls")]
	public partial class AboutUsControls : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "aboutUsControls";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutUsControls, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AboutUsControls(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// AboutHead
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("aboutHead")]
		public string AboutHead => this.Value<string>("aboutHead");

		///<summary>
		/// AboutSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("aboutSub")]
		public string AboutSub => this.Value<string>("aboutSub");

		///<summary>
		/// TabLeftSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("aboutTabLeftSub")]
		public string AboutTabLeftSub => this.Value<string>("aboutTabLeftSub");

		///<summary>
		/// AboutThemeslat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("aboutThemeslat")]
		public IEnumerable<AboutUsThemeslatList> AboutThemeslat => this.Value<IEnumerable<AboutUsThemeslatList>>("aboutThemeslat");

		///<summary>
		/// CounterThemeslat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("counterThemeslat")]
		public IEnumerable<AboutUsThemeslatList> CounterThemeslat => this.Value<IEnumerable<AboutUsThemeslatList>>("counterThemeslat");

		///<summary>
		/// IconBoxHead
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iconBoxHead")]
		public string IconBoxHead => this.Value<string>("iconBoxHead");

		///<summary>
		/// IconBoxList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iconBoxList")]
		public IEnumerable<AboutUsIcoinList> IconBoxList => this.Value<IEnumerable<AboutUsIcoinList>>("iconBoxList");

		///<summary>
		/// IconBoxSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iconBoxSub")]
		public string IconBoxSub => this.Value<string>("iconBoxSub");

		///<summary>
		/// QuotePhone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quotePhone")]
		public string QuotePhone => this.Value<string>("quotePhone");

		///<summary>
		/// QuoteSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quoteSub")]
		public string QuoteSub => this.Value<string>("quoteSub");

		///<summary>
		/// TabLeftSubDetailList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabLeftSubDetailList")]
		public IEnumerable<AboutTabItemList> TabLeftSubDetailList => this.Value<IEnumerable<AboutTabItemList>>("tabLeftSubDetailList");

		///<summary>
		/// TabLeftSubList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabLeftSubList")]
		public IEnumerable<AboutUsThemeslatList> TabLeftSubList => this.Value<IEnumerable<AboutUsThemeslatList>>("tabLeftSubList");

		///<summary>
		/// TabRightHead
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabRightHead")]
		public string TabRightHead => this.Value<string>("tabRightHead");

		///<summary>
		/// TabRightSubList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabRightSubList")]
		public IEnumerable<AboutTabAccordinItemList> TabRightSubList => this.Value<IEnumerable<AboutTabAccordinItemList>>("tabRightSubList");

		///<summary>
		/// TeamHead
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("teamHead")]
		public string TeamHead => this.Value<string>("teamHead");

		///<summary>
		/// TeamItemList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("teamItemList")]
		public IEnumerable<AboutTeamList> TeamItemList => this.Value<IEnumerable<AboutTeamList>>("teamItemList");

		///<summary>
		/// TeamSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("teamSub")]
		public string TeamSub => this.Value<string>("teamSub");
	}
}
