//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.NoiThat.Core
{
	/// <summary>About us</summary>
	[PublishedModel("aboutUs")]
	public partial class AboutUs : PublishedContentModel, IAboutUsControls, IGeneralControls, IGeneralSlideImage, ISEocontrols
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "aboutUs";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutUs, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AboutUs(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// AboutHead
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("aboutHead")]
		public string AboutHead => AboutUsControls.GetAboutHead(this);

		///<summary>
		/// AboutSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("aboutSub")]
		public string AboutSub => AboutUsControls.GetAboutSub(this);

		///<summary>
		/// TabLeftSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("aboutTabLeftSub")]
		public string AboutTabLeftSub => AboutUsControls.GetAboutTabLeftSub(this);

		///<summary>
		/// AboutThemeslat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("aboutThemeslat")]
		public IEnumerable<AboutUsThemeslatList> AboutThemeslat => AboutUsControls.GetAboutThemeslat(this);

		///<summary>
		/// CounterThemeslat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("counterThemeslat")]
		public IEnumerable<AboutUsCounterThemeSlat> CounterThemeslat => AboutUsControls.GetCounterThemeslat(this);

		///<summary>
		/// IconBoxHead
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iconBoxHead")]
		public string IconBoxHead => AboutUsControls.GetIconBoxHead(this);

		///<summary>
		/// IconBoxList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iconBoxList")]
		public IEnumerable<AboutUsIcoinList> IconBoxList => AboutUsControls.GetIconBoxList(this);

		///<summary>
		/// IconBoxSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iconBoxSub")]
		public string IconBoxSub => AboutUsControls.GetIconBoxSub(this);

		///<summary>
		/// QuotePhone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quotePhone")]
		public string QuotePhone => AboutUsControls.GetQuotePhone(this);

		///<summary>
		/// QuoteSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quoteSub")]
		public string QuoteSub => AboutUsControls.GetQuoteSub(this);

		///<summary>
		/// TabLeftSubDetailList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabLeftSubDetailList")]
		public IEnumerable<AboutTabItemList> TabLeftSubDetailList => AboutUsControls.GetTabLeftSubDetailList(this);

		///<summary>
		/// TabLeftSubList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabLeftSubList")]
		public IEnumerable<AboutUsThemeslatList> TabLeftSubList => AboutUsControls.GetTabLeftSubList(this);

		///<summary>
		/// TabRightHead
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabRightHead")]
		public string TabRightHead => AboutUsControls.GetTabRightHead(this);

		///<summary>
		/// TabRightSubList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabRightSubList")]
		public IEnumerable<AboutTabAccordinItemList> TabRightSubList => AboutUsControls.GetTabRightSubList(this);

		///<summary>
		/// TeamHead
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("teamHead")]
		public string TeamHead => AboutUsControls.GetTeamHead(this);

		///<summary>
		/// TeamItemList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("teamItemList")]
		public IEnumerable<AboutTeamList> TeamItemList => AboutUsControls.GetTeamItemList(this);

		///<summary>
		/// TeamSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("teamSub")]
		public string TeamSub => AboutUsControls.GetTeamSub(this);

		///<summary>
		/// PageMainDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pageMainDescription")]
		public IHtmlString PageMainDescription => GeneralControls.GetPageMainDescription(this);

		///<summary>
		/// PageMainImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pageMainImage")]
		public IPublishedContent PageMainImage => GeneralControls.GetPageMainImage(this);

		///<summary>
		/// Page Short Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pageShortContent")]
		public IHtmlString PageShortContent => GeneralControls.GetPageShortContent(this);

		///<summary>
		/// PageTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => GeneralControls.GetPageTitle(this);

		///<summary>
		/// umbracoNaviHide
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide => GeneralControls.GetUmbracoNaviHide(this);

		///<summary>
		/// General Slide List Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("generalSlideListImage")]
		public IEnumerable<SildeImageItem> GeneralSlideListImage => GeneralSlideImage.GetGeneralSlideListImage(this);

		///<summary>
		/// Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => SEocontrols.GetMetaDescription(this);

		///<summary>
		/// Meta Keywords
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("metaKeywords")]
		public IEnumerable<string> MetaKeywords => SEocontrols.GetMetaKeywords(this);

		///<summary>
		/// Meta Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("metaName")]
		public string MetaName => SEocontrols.GetMetaName(this);
	}
}
