//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.NoiThat.Core
{
	// Mixin Content Type with alias "contactControls"
	/// <summary>Contact Controls</summary>
	public partial interface IContactControls : IPublishedContent
	{
		/// <summary>ContactTopHeading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string ContactTopHeading { get; }

		/// <summary>ContactTopSub</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string ContactTopSub { get; }

		/// <summary>ContactUnderHeading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string ContactUnderHeading { get; }

		/// <summary>ContactUnderInformation</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IEnumerable<ContactInfomationList> ContactUnderInformation { get; }
	}

	/// <summary>Contact Controls</summary>
	[PublishedModel("contactControls")]
	public partial class ContactControls : PublishedContentModel, IContactControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "contactControls";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactControls, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ContactControls(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// ContactTopHeading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactTopHeading")]
		public string ContactTopHeading => GetContactTopHeading(this);

		/// <summary>Static getter for ContactTopHeading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetContactTopHeading(IContactControls that) => that.Value<string>("contactTopHeading");

		///<summary>
		/// ContactTopSub
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactTopSub")]
		public string ContactTopSub => GetContactTopSub(this);

		/// <summary>Static getter for ContactTopSub</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetContactTopSub(IContactControls that) => that.Value<string>("contactTopSub");

		///<summary>
		/// ContactUnderHeading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUnderHeading")]
		public string ContactUnderHeading => GetContactUnderHeading(this);

		/// <summary>Static getter for ContactUnderHeading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetContactUnderHeading(IContactControls that) => that.Value<string>("contactUnderHeading");

		///<summary>
		/// ContactUnderInformation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUnderInformation")]
		public IEnumerable<ContactInfomationList> ContactUnderInformation => GetContactUnderInformation(this);

		/// <summary>Static getter for ContactUnderInformation</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IEnumerable<ContactInfomationList> GetContactUnderInformation(IContactControls that) => that.Value<IEnumerable<ContactInfomationList>>("contactUnderInformation");
	}
}
