//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.NoiThat.Core
{
	// Mixin Content Type with alias "featureProjectsControls"
	/// <summary>Feature Projects  Controls</summary>
	public partial interface IFeatureProjectsControls : IPublishedContent
	{
		/// <summary>FeatureProjectContentList</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IEnumerable<FeatureProjectContentItem> FeatureProjectContentList { get; }

		/// <summary>Feature Project Intro</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string FeatureProjectIntro { get; }
	}

	/// <summary>Feature Projects  Controls</summary>
	[PublishedModel("featureProjectsControls")]
	public partial class FeatureProjectsControls : PublishedContentModel, IFeatureProjectsControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "featureProjectsControls";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FeatureProjectsControls, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public FeatureProjectsControls(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// FeatureProjectContentList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featureProjectContentList")]
		public IEnumerable<FeatureProjectContentItem> FeatureProjectContentList => GetFeatureProjectContentList(this);

		/// <summary>Static getter for FeatureProjectContentList</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IEnumerable<FeatureProjectContentItem> GetFeatureProjectContentList(IFeatureProjectsControls that) => that.Value<IEnumerable<FeatureProjectContentItem>>("featureProjectContentList");

		///<summary>
		/// Feature Project Intro
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featureProjectIntro")]
		public string FeatureProjectIntro => GetFeatureProjectIntro(this);

		/// <summary>Static getter for Feature Project Intro</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetFeatureProjectIntro(IFeatureProjectsControls that) => that.Value<string>("featureProjectIntro");
	}
}
