//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.NoiThat.Core
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Home(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// HomeAboutUsCoverImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeAboutUsCoverImage")]
		public IPublishedContent HomeAboutUsCoverImage => this.Value<IPublishedContent>("homeAboutUsCoverImage");

		///<summary>
		/// HomeAboutUsDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeAboutUsDescription")]
		public IHtmlString HomeAboutUsDescription => this.Value<IHtmlString>("homeAboutUsDescription");

		///<summary>
		/// HomeAboutUsTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeAboutUsTitle")]
		public string HomeAboutUsTitle => this.Value<string>("homeAboutUsTitle");

		///<summary>
		/// HomeSlideImageOne
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeSlideImageOne")]
		public IPublishedContent HomeSlideImageOne => this.Value<IPublishedContent>("homeSlideImageOne");

		///<summary>
		/// HomeSlideImageOneTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeSlideImageOneTitle")]
		public string HomeSlideImageOneTitle => this.Value<string>("homeSlideImageOneTitle");

		///<summary>
		/// HomeSlideImageThree
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeSlideImageThree")]
		public IPublishedContent HomeSlideImageThree => this.Value<IPublishedContent>("homeSlideImageThree");

		///<summary>
		/// HomeSlideImageThreeTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeSlideImageThreeTitle")]
		public string HomeSlideImageThreeTitle => this.Value<string>("homeSlideImageThreeTitle");

		///<summary>
		/// HomeSlideImageTrue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeSlideImageTrue")]
		public IPublishedContent HomeSlideImageTrue => this.Value<IPublishedContent>("homeSlideImageTrue");

		///<summary>
		/// HomeSlideImageTrueTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("homeSlideImageTrueTitle")]
		public string HomeSlideImageTrueTitle => this.Value<string>("homeSlideImageTrueTitle");
	}
}
